//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplicationDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Comment_Id { get; set; }
        public int Post_id { get; set; }
        public int User_id { get; set; }
        public string Content { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> Votes { get; set; }
        public string Reported { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
