//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplicationDatabase.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Question
    {
        public Question()
        {
            this.Posts = new HashSet<Post>();
            this.Tags = new HashSet<Tag>();
        }
    
        public int Question_id { get; set; }
        public Nullable<int> BestAnswer_id { get; set; }
        public System.DateTime DateCreated { get; set; }
        [Required]
        public string Title { get; set; }
        public int Views { get; set; }
        public string Reported { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Post> Posts { get; set; }
        public virtual Post BestAnswer { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
