//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplicationDatabase.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Tag
    {
        public Tag()
        {
            this.Questions = new HashSet<Question>();
        }
    
        public int Tag_id { get; set; }
        [Required]
        public string Name { get; set; }
        public string Summary { get; set; }
    
        public virtual ICollection<Question> Questions { get; set; }
    }
}
